# Generated by Django 6.0.2 on 2026-02-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liar_id",
                    models.CharField(
                        help_text="Dataset statement id (e.g., 12134.json).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("true", "true"),
                            ("mostly-true", "mostly-true"),
                            ("half-true", "half-true"),
                            ("barely-true", "barely-true"),
                            ("false", "false"),
                            ("pants-fire", "pants-fire"),
                        ],
                        db_index=True,
                        help_text="Truthfulness label from LIAR dataset.",
                        max_length=20,
                    ),
                ),
                (
                    "statement",
                    models.TextField(help_text="The claim text / statement."),
                ),
                (
                    "subjects",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated subjects/topics.",
                        max_length=255,
                    ),
                ),
                (
                    "speaker",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Speaker name/id (as in dataset).",
                        max_length=100,
                    ),
                ),
                (
                    "speaker_job_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Speaker job title (may be empty).",
                        max_length=150,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="State information (may be empty).",
                        max_length=60,
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Party affiliation (may be empty, e.g., republican/democrat/none).",
                        max_length=60,
                    ),
                ),
                ("barely_true_count", models.PositiveIntegerField(default=0)),
                ("false_count", models.PositiveIntegerField(default=0)),
                ("half_true_count", models.PositiveIntegerField(default=0)),
                ("mostly_true_count", models.PositiveIntegerField(default=0)),
                ("pants_on_fire_count", models.PositiveIntegerField(default=0)),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Context/venue/location of the statement.",
                        max_length=255,
                    ),
                ),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("train", "Train"),
                            ("valid", "Validation"),
                            ("test", "Test"),
                        ],
                        db_index=True,
                        help_text="Dataset split (train/valid/test).",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
