# Generated by Django 6.0.2 on 2026-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liar_id", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=20)),
                ("statement", models.TextField()),
                ("speaker", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
