"""
Django settings for credibility_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Standard Python and Django utilities used for:
# - resolving project file paths
# - accessing environment variables
# - detecting test environments
# - configuring the database using DATABASE_URL (used in deployment)
from pathlib import Path
import sys
import os
import dj_database_url


# Detect when the project is running in test mode.
# This allows certain features (such as API throttling) to be disabled
# during automated tests so they do not interfere with test execution.
TESTING = "test" in sys.argv

# BASE_DIR represents the root directory of the Django project.
# It is used to construct absolute paths for files such as
# the database, static files and templates.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secret key used by Django for cryptographic signing.
# In production this is loaded from an environment variable
# to avoid exposing sensitive security information in the codebase.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key-please-change-123456789"
)

# Debug mode controls whether detailed error pages are shown.
# It should be enabled during development but disabled in production
# for security reasons.
DEBUG = os.environ.get("DEBUG", "False") == "True"


# Specifies which host/domain names are allowed to serve this Django app.
# This prevents HTTP Host header attacks.
# The '.onrender.com' entry allows the API to run on the Render deployment platform.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]

# Application definition
INSTALLED_APPS = [
    # Allows cross-origin requests from the frontend application
    "corsheaders",
    # provides the Django REST Framework used to build the API
    "rest_framework",
    # enables advanced query filtering for API endpoints
    "django_filters",
    # the custom application containing claim models, scoring logic,
    # dataset retrieval, and reporting functionality
    "claims",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # generates OpenAPI/Swagger documentation for the API
    "drf_spectacular",
]

# Middleware components process requests and responses globally.
# These handle security, session management, authentication,
# CORS policy handling, and static file serving.
MIDDLEWARE = [
    # Allows requests from external frontends (e.g. the React frontend).
    "corsheaders.middleware.CorsMiddleware",
    # Serves static files efficiently in production environments.
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "credibility_api.urls"

# Template configuration used for rendering HTML pages.
# While the project is primarily an API, templates allow
# the Django REST Framework browsable API interface to work.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "credibility_api" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "credibility_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# The project uses SQLite for local development.
# During deployment, dj_database_url allows the database
# to be configured via a DATABASE_URL environment variable,
# which supports PostgreSQL or other production databases.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Django REST Framework configuration.
# These settings control authentication, permissions,
# pagination, filtering, rate limiting and schema generation
# for all API endpoints.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,

    # Rate limiting protects the API from abuse by restricting
    # how many requests a client can make within a time window.
    # Throttling is disabled during automated tests.
    "DEFAULT_THROTTLE_CLASSES": [] if TESTING else [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {} if TESTING else {
        "anon": "100/hour",
        "user": "500/hour",
        "score": "15/hour",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Credibility Intelligence API",
    "DESCRIPTION": "A REST API for browsing claims analysing credibility scores, and managing user reports.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

LOGIN_REDIRECT_URL = "/api/"
LOGOUT_REDIRECT_URL = "/api/"

# Allows cross-origin requests to the API.
# This is required for the frontend application to communicate
# with the backend API from a different domain.
CORS_ALLOW_ALL_ORIGINS = True

# Explicit list of frontend domains permitted to access the API.
# Includes both local development environments and the deployed frontend.
CORS_ALLOWED_ORIGINS = [
    "https://credibility-intelligence-frontend.onrender.com",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]

# Trusted domains allowed to perform cross-site requests
# when CSRF protection is enabled.
# Required for deployed environments such as Render.
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]
